Update CAM_1_pl.txt line 6-7
RybazPolski/IA-LoA-PL pull request #29
Opened 2023-12-30 11:43 UTC by MikolajRutkowski

2024-01-02 17:43 UTC, RybazPolski commented
W pewnych miejscach pojawia się {0}'s - na miejscu {0} pojawia się nazwa figurki, a 's no to fragment od possesive'a.

Jednak ponieważ w polskim odmiany są bardzo różne:
"na polu Garkhan**a**", ale za razem "na polu Dial**i** Passil"

proponuję coś w deseń: "na polu**, na którym stoi** Gaarkhan"

2024-01-05 17:26 UTC, MikolajRutkowski commented
> W pewnych miejscach pojawia się {0}'s - na miejscu {0} pojawia się nazwa figurki, a 's no to fragment od possesive'a.
> 
> Jednak ponieważ w polskim odmiany są bardzo różne: "na polu Garkhan**a**", ale za razem "na polu Dial**i** Passil"
> 
> proponuję coś w deseń: "na polu, **na którym stoi** Gaarkhan" (a 's skasujemy)

2024-01-05 17:28 UTC, MikolajRutkowski commented
> W pewnych miejscach pojawia się {0}'s - na miejscu {0} pojawia się nazwa figurki, a 's no to fragment od possesive'a.
> 
> Jednak ponieważ w polskim odmiany są bardzo różne: "na polu Garkhan**a**", ale za razem "na polu Dial**i** Passil"
> 
> proponuję coś w deseń: "na polu, **na którym stoi** Gaarkhan" (a 's skasujemy)

Zrobiłem tak jak pisałeś, przetłumaczyłem też następne linijki, probe droids  przetłumaczyłem tak jak jest w Imperial Comaderze jest czyli "Sonda szpiegowska"

2024-01-05 17:59 UTC, RybazPolski requested changes

2024-01-05 17:59 UTC, RybazPolski commented on translatedTextAssets/CAM_1_pl.txt
> +M_01_MAJOR_PERIL_2,"[b]Duże niebezpieczeństwo[/b]\n\n[i]Granat uderzeniowy ląduje na na którym stoi {0}’s i eksploduje..[/i]\n\nRzuć 1 żółtą kością. Każda figurka na lub obok pola na którym stoi {0}’
jeszcze **'s** zza **{0}** przydałoby się zdjąć

2024-01-05 18:32 UTC, MikolajRutkowski commented on translatedTextAssets/CAM_1_pl.txt
> +M_01_MAJOR_PERIL_2,"[b]Duże niebezpieczeństwo[/b]\n\n[i]Granat uderzeniowy ląduje na na którym stoi {0}’s i eksploduje..[/i]\n\nRzuć 1 żółtą kością. Każda figurka na lub obok pola na którym stoi {0}’
Done

2024-01-05 18:42 UTC, RybazPolski requested changes

2024-01-05 18:42 UTC, RybazPolski commented on translatedTextAssets/CAM_1_pl.txt
> +M_01_MAJOR_PERIL_2,"[b]Duże niebezpieczeństwo[/b]\n\n[i]Granat uderzeniowy ląduje na na którym stoi {0} i eksploduje..[/i]\n\nRzuć 1 żółtą kością. Każda figurka na lub obok pola na którym stoi {0} ot
jeeeszcze jedną drobnostkę teraz się kapnąłem - dwie kropki się wstawiły po "eksploduje"

2024-01-05 18:52 UTC, MikolajRutkowski commented on translatedTextAssets/CAM_1_pl.txt
> +M_01_MAJOR_PERIL_2,"[b]Duże niebezpieczeństwo[/b]\n\n[i]Granat uderzeniowy ląduje na na którym stoi {0} i eksploduje..[/i]\n\nRzuć 1 żółtą kością. Każda figurka na lub obok pola na którym stoi {0} ot
Done

2024-01-05 19:11 UTC, RybazPolski commented
Merguję :)

2024-01-05 19:11 UTC, merged